name: CI
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@2.11.0
      - run: composer install
      - run: ./vendor/bin/phpstan analyze ./*.php --level 8 --memory-limit 10
