name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        name: Add SSH key
      - uses: actions/setup-node@v2
        name: Install Node
      - run: yarn install
      - run: yarn build
        env:
          NODE_ENV: production
      - run: 'echo "${{ secrets.ENV_JSON }}" > env.json'
      - run: rsync --exclude ".git/" --exclude "node_modules/" -e "ssh -o StrictHostKeyChecking=no" -r ./* root@165.227.96.87:/home/cjdenio/trip/wp-content/themes/trip
        name: Deploy
